version: '3'

services:
  bda-app-rm:
    image: '_docker_hub_iamge_url/bda-app-rm:_image_version'
    ports:
      - '8101:8101/tcp'
    restart: always
    environment:
      - missionControlServiceUrl=_mission_control_service_url
    volumes:
      - '/etc/hosts:/etc/hosts:rw'
      - '/etc/localtime:/etc/localtime:rw'
