version: '3'

services:
  bda-app-data:
    image: '_docker_hub_iamge_url/bda-app-data:_image_version'
    ports:
      - 8100:8080/tcp'
    restart: always
    environment:
      - logServiceUrl=http://_log_service_ip:8096'
      - dataServiceHost=_data_service_ip
      - dataServicePort=8100
      - jerseyHost=_redis_ip
      - jerseyPort=6380
      - stagingHost=_postgres_ip
      - stagingUserName=_postgres_user_name
      - stagingPassword=_postgres_password
      - stagingPort=_postgres_port
      - stagingDefaultDatabase=postgres
      - semanticServiceUrl=http://_semantic_service_ip:8091
      - giantServiceEndPointUrl=http://_giant_service_ip/WebAPIs/GiantService
      - dmServiceUrl=http://_dm_service_ip:8099'
      - missionControlServiceUrl=_mission_control_service_ip
      - region1=_region1
    volumes:
      - '/etc/hosts:/etc/hosts:rw'
      - '/etc/localtime:/etc/localtime:rw'
