version: '3'

services:
  bda-app-messaging:
    restart: always
    ports:
      - '8097:8080/tcp'
    environment:
      - logServiceUrl=http://_log_service_ip:8096
      - pathMessagingStorage=opt/bda/messaging/
      - missionControlServiceUrl=_mission_control_service_url
      - region1=_region1
    image: '_docker_hub_iamge_url/bda-app-messaging:_image_version'
    volumes:
      - '/etc/localtime:/etc/localtime:rw'
      - '/etc/hosts:/etc/hosts:rw'
