version: '3'

services:
  bda-app-data:
    image: '_docker_hub_iamge_url/bda-app-data:_image_version'
    ports:
      - 8100:8080/tcp'
    restart: always
    environment:
      - semanticServiceUrl=http://_semantic_service_ip:8091
      - missionControlServiceUrl=_mission_control_service_ip
      - region1=_region1
    volumes:
      - '/etc/hosts:/etc/hosts:rw'
      - '/etc/localtime:/etc/localtime:rw'
