version: '3'

services:
  bda-app-messagingagent:
    restart: always
    environment:
      - missionControlServiceUrl=_mission_control_service_url
      - region1=_region1
    image: '_docker_hub_iamge_url/bda-app-messagingagent:_image_version'
    volumes:
      - '/etc/localtime:/etc/localtime:rw'
      - '/etc/hosts:/etc/hosts'
      - '/opt/bda/datasource/:/opt/datasource/:rw'
