version: '3'

services:
  bda-app-semantic:
    restart: always
    ports:
      - '8091:8080/tcp'
    environment:
      - dataServiceUrl=http://_data_service_ip:8100
      - searchServiceUrl=http://_data_search_ip:8095     
      - missionControlServiceUrl=_mission_control_service_url
      - missionControlAccountUrl=_mission_control_account_url
    image: '_docker_hub_iamge_url/bda-app-semantic:_image_version'
    volumes:
      - '/etc/localtime:/etc/localtime:rw'
      - '/etc/hosts:/etc/hosts:rw'
