version: '3'

services:
  bda-app-dm:
    image: '_docker_hub_iamge_url/bda-app-dm:2.8.0.61'
    ports:
      - '8099:8080/tcp'
    restart: always
    environment:
      - semanticServiceUrl=http://_semantic_service_ip:8091
      - missionControlServiceUrl=_mission_control_service_url
    volumes:
      - '/etc/hosts:/etc/hosts:rw'
      - '/etc/localtime:/etc/localtime:rw'
