version: '3'

services:
  datamanipulation:
    image: '_docker_hub_iamge_url:_image_version'
    ports:
      - '8017:8017/tcp'
    restart: always
    environment:
      - semanticServiceUrl=http://_semantic_service_ip:8091
      - applicationWebRootPath=_applicationWebRootPath
      - orientDbHostConfig=_orientdb_host
      - orientDbPortConfig=2424
      - orientDbDatabaseConfig=DataManipulation
      - orientDbUsernameConfig=_orientdb_user_name
      - orientDbPasswordConfig=_orientdb_password
      - orientDbMinSizeOfPoolConfig=0
      - orientDbMaxSizeOfPoolConfig=100
      - webPort=8017 
    volumes:
      - '/etc/hosts:/etc/hosts:rw'
      - '/etc/localtime:/etc/localtime:rw'
