version: '3'

services:
  tasker:
    image: '_docker_hub_iamge_url/tasker:_image_version'
    ports:
      - '8090:8090/tcp'
    restart: always
    environment:
      - missionControlServiceUrl=_mission_control_service_url
      - dataSearchUrl=http://_data_search_ip:8100
    volumes:
      - '/etc/hosts:/etc/hosts:rw'
      - '/etc/localtime:/etc/localtime:rw'
